var skillsList = {
      "Acrobatics": "Dexterity",
      "Appraise": "Intelligence",
      "Bluff": "Charisma",
      "Climb": "Strength",
      "Craft": "Intelligence",
      "Craft": "Intelligence",
      "Craft": "Intelligence",
      "Diplomacy": "Charisma",
      "Disable Device*": "Dexterity",
      "Disguise": "Charisma",
      "Escape Artist": "Dexterity",
      "Fly": "Dexterity",
      "Handle Animal*": "Charisma",
      "Heal": "Wisdom",
      "Intimidate": "Charisma",
      "Knowledge (Arcana)*": "Intelligence",
      "Knowledge (Dungeoneering)*": "Intelligence",
      "Knowledge (Engineering)*": "Intelligence",
      "Knowledge (Geography)*": "Intelligence",
      "Knowledge (History)*": "Intelligence",
      "Knowledge (Local)*": "Intelligence",
      "Knowledge (Nature)*": "Intelligence",
      "Knowledge (Nobility)*": "Intelligence",
      "Knowledge (Planes)*": "Intelligence",
      "Knowledge (Religion)*": "Intelligence",
      "Linguistics*": "Intelligence",
      "Perception": "Wisdom",
      "Perform": "Charisma",
      "Perform": "Charisma",
      "Profession*": "Wisdom",
      "Profession*": "Wisdom",
      "Ride": "Dexterity",
      "Sense Motive": "Wisdom",
      "Sleight of Hand*": "Dexterity",
      "Spellcraft*": "Intelligence",
      "Stealth": "Dexterity",
      "Survival": "Wisdom",
      "Swim": "Strength",
      "Use Magic Device*":"Charisma",
      "Ranger": {
            "ClassAcrobatics": 0,
            "ClassAppraise": 0,
            "ClassBluff": 0,
            "ClassClimb": 3,
            "ClassCraft": 3,
            "ClassCraft": 0,
            "ClassCraft": 0,
            "ClassDiplomacy": 0,
            "ClassDisable Device*": 0,
            "ClassDisguise": 0,
            "ClassEscape Artist": 0,
            "ClassFly": 0,
            "ClassHandle Animal*": 3,
            "ClassHeal": 3,
            "ClassIntimidate": 3,
            "ClassKnowledge (Arcana)*": 0,
            "ClassKnowledge (Dungeoneering)*": 3,
            "ClassKnowledge (Engineering)*": 0,
            "ClassKnowledge (Geography)*": 3,
            "ClassKnowledge (History)*": 0,
            "ClassKnowledge (Local)*": 0,
            "ClassKnowledge (Nature)*": 3,
            "ClassKnowledge (Nobility)*": 0,
            "ClassKnowledge (Planes)*": 0,
            "ClassKnowledge (Religion)*": 0,
            "ClassLinguistics*": 0,
            "ClassPerception": 3,
            "ClassPerform": 0,
            "ClassPerform": 0,
            "ClassProfession*": 3,
            "ClassProfession*": 0,
            "ClassRide": 3, 
            "ClassSense Motive": 0,
            "ClassSleight of Hand*": 0,
            "ClassSpellcraft*": 3,
            "ClassStealth": 3,
            "ClassSurvival": 3,
            "ClassSwim": 3,
            "ClassUse Magic Device*": 0,
            }, 

    };