var skillsList = {
      "Acrobatics": "Dexterity",
      "Appraise": "Intelligence",
      "Bluff": "Charisma",
      "Climb": "Strength",
      "Craft1": "Intelligence",
      "Craft2": "Intelligence",
      "Craft3": "Intelligence",
      "Diplomacy": "Charisma",
      "Disable Device*": "Dexterity",
      "Disguise": "Charisma",
      "Escape Artist": "Dexterity",
      "Fly": "Dexterity",
      "Handle Animal*": "Charisma",
      "Heal": "Wisdom",
      "Intimidate": "Charisma",
      "Knowledge (Arcana)*": "Intelligence",
      "Knowledge (Dungeoneering)*": "Intelligence",
      "Knowledge (Engineering)*": "Intelligence",
      "Knowledge (Geography)*": "Intelligence",
      "Knowledge (History)*": "Intelligence",
      "Knowledge (Local)*": "Intelligence",
      "Knowledge (Nature)*": "Intelligence",
      "Knowledge (Nobility)*": "Intelligence",
      "Knowledge (Planes)*": "Intelligence",
      "Knowledge (Religion)*": "Intelligence",
      "Linguistics*": "Intelligence",
      "Perception": "Wisdom",
      "Perform1": "Charisma",
      "Perform2": "Charisma",
      "Profession1": "Wisdom",
      "Profession2": "Wisdom",
      "Ride": "Dexterity",
      "Sense Motive": "Wisdom",
      "Sleight of Hand*": "Dexterity",
      "Spellcraft*": "Intelligence",
      "Stealth": "Dexterity",
      "Survival": "Wisdom",
      "Swim": "Strength",
      "Use Magic Device*":"Charisma",

    };